version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "opayo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9ull0n1xux5z"
s3_prefix = "opayo"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "IAMUsername=\"Administrator\" OpayoSG=\"sg-0df6213c185e5660b\" OpayoSubnets=\"subnet-0ec3738deca752f86,subnet-04ebc81bb90dd5fd6,subnet-086f16f28802b7fc4\" DBInstanceID=\"OpayoDBInstance\" DBName=\"opayo\" DBInstanceClass=\"db.t2.micro\" DBAllocatedStorage=\"20\""
