AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  opayo-test

  Sample SAM Template for opayo-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  OpayoTestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: opayo_test/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        OpayoTest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /transactions
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  OpayoTestApi:
    Description: "API Gateway endpoint URL for Prod stage for Opayo technical test function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/transactions/"
  OpayoTestFunction:
    Description: "Opayo Test Lambda Function ARN"
    Value: !GetAtt OpayoTestFunction.Arn
  OpayoTestFunctionIamRole:
    Description: "Implicit IAM Role created for Opayo Test function"
    Value: !GetAtt OpayoTestFunctionRole.Arn
